In [1]:
import numpy as np
import pandas as pd

from portfoliobuilder.ranking import get_measures

In [9]:
QUALITY_MEASURES = ['profit_margin', 'revenue_growth', 'ebitda_growth', 
        'roe_income', 'roaa_income', 'roic_income', 'roe_ebitda', 
        'roa_ebitda', 'roic_ebitda', 'current_ratio', 'assets_to_liabilities']

In [2]:
measures_series = get_measures('AAPL')

In [5]:
fb_measures_series = get_measures('FB')

In [18]:
nflx_measures_series = get_measures('NFLX')

In [19]:
aapl_measures_series
fb_measures_series
nflx_measures_series

pe_ttm                   62.825170
ev_ebitda                13.351000
p_fcf_last_year          -0.000072
ev_fcf                   16.213300
ps_ttm                    8.548620
ev_s                      7.953868
pb                       17.510180
profit_margin             7.880950
revenue_growth           29.817910
ebitda_growth            33.940320
roe_income                9.767770
roaa_income               0.061000
roic_income               0.298000
roe_ebitda                1.829645
roa_ebitda                0.353431
roic_ebitda               1.330320
current_ratio             1.269510
assets_to_liabilities     1.287273
Name: NFLX, dtype: float64

In [84]:
df = pd.concat([aapl_measures_series, fb_measures_series, nflx_measures_series], axis=1)

In [85]:
df

                            AAPL         FB       NFLX
pe_ttm                 26.913490  24.883030  62.825170
ev_ebitda              14.875000  19.262000  13.351000
p_fcf_last_year         0.000038   0.000044  -0.000072
ev_fcf                 35.736380  34.919490  16.213300
ps_ttm                  6.856470   9.980900   8.548620
ev_s                    4.475888   8.324256   7.953868
pb                     32.249540   7.063120  17.510180
profit_margin          21.502190  34.960880   7.880950
revenue_growth          3.270410  36.822640  29.817910
ebitda_growth          -1.097100  37.055540  33.940320
roe_income             23.210420  22.352220   9.767770
roaa_income             0.161000   0.153000   0.061000
roic_income             0.212000   0.301000   0.298000
roe_ebitda              0.762452   0.330007   1.829645
roa_ebitda              0.231256   0.229074   0.353431
roic_ebitda             0.252389   0.370493   1.330320
current_ratio           1.141750   6.080210   1.269510
assets_to_liabilities   1.364830   4.126477   1.287273

In [86]:
measure_type_col = ['quality' if i in QUALITY_MEASURES else 'valuation' for i in df.index]
df['measure_type'] = measure_type_col
df

                            AAPL         FB       NFLX measure_type
pe_ttm                 26.913490  24.883030  62.825170    valuation
ev_ebitda              14.875000  19.262000  13.351000    valuation
p_fcf_last_year         0.000038   0.000044  -0.000072    valuation
ev_fcf                 35.736380  34.919490  16.213300    valuation
ps_ttm                  6.856470   9.980900   8.548620    valuation
ev_s                    4.475888   8.324256   7.953868    valuation
pb                     32.249540   7.063120  17.510180    valuation
profit_margin          21.502190  34.960880   7.880950      quality
revenue_growth          3.270410  36.822640  29.817910      quality
ebitda_growth          -1.097100  37.055540  33.940320      quality
roe_income             23.210420  22.352220   9.767770      quality
roaa_income             0.161000   0.153000   0.061000      quality
roic_income             0.212000   0.301000   0.298000      quality
roe_ebitda              0.762452   0.330007   1.829645      quality
roa_ebitda              0.231256   0.229074   0.353431      quality
roic_ebitda             0.252389   0.370493   1.330320      quality
current_ratio           1.141750   6.080210   1.269510      quality
assets_to_liabilities   1.364830   4.126477   1.287273      quality

In [87]:
valuation_max = df[df['measure_type'] == 'valuation'].max(axis=1)

df.iloc[0, 0] = np.nan
df.iloc[3, 1] = np.nan

for measure in valuation_max.index:
    df.loc[measure] = df.loc[measure].fillna(valuation_max.loc[measure], inplace=False)

df

                            AAPL         FB       NFLX measure_type
pe_ttm                 62.825170  24.883030  62.825170    valuation
ev_ebitda              14.875000  19.262000  13.351000    valuation
p_fcf_last_year         0.000038   0.000044  -0.000072    valuation
ev_fcf                 35.736380  35.736380  16.213300    valuation
ps_ttm                  6.856470   9.980900   8.548620    valuation
ev_s                    4.475888   8.324256   7.953868    valuation
pb                     32.249540   7.063120  17.510180    valuation
profit_margin          21.502190  34.960880   7.880950      quality
revenue_growth          3.270410  36.822640  29.817910      quality
ebitda_growth          -1.097100  37.055540  33.940320      quality
roe_income             23.210420  22.352220   9.767770      quality
roaa_income             0.161000   0.153000   0.061000      quality
roic_income             0.212000   0.301000   0.298000      quality
roe_ebitda              0.762452   0.330007   1.829645      quality
roa_ebitda              0.231256   0.229074   0.353431      quality
roic_ebitda             0.252389   0.370493   1.330320      quality
current_ratio           1.141750   6.080210   1.269510      quality
assets_to_liabilities   1.364830   4.126477   1.287273      quality

In [69]:
df.iloc[:,:-1].loc[['pe_ttm']]

            AAPL        FB      NFLX
pe_ttm  62.82517  24.88303  62.82517

In [74]:
mins = df.min(axis=1)
mins

pe_ttm                   24.883030
ev_ebitda                13.351000
p_fcf_last_year          -0.000072
ev_fcf                   16.213300
ps_ttm                    6.856470
ev_s                      4.475888
pb                        7.063120
profit_margin             7.880950
revenue_growth            3.270410
ebitda_growth            -1.097100
roe_income                9.767770
roaa_income               0.061000
roic_income               0.212000
roe_ebitda                0.330007
roa_ebitda                0.229074
roic_ebitda               0.252389
current_ratio             1.141750
assets_to_liabilities     1.287273
dtype: float64

In [88]:
symbols_cols = [True for i in range(len(df.columns)-1)]
symbols_cols.append(False)
df_no_measure_type = df.loc[:,symbols_cols].copy()
df_no_measure_type

                            AAPL         FB       NFLX
pe_ttm                 62.825170  24.883030  62.825170
ev_ebitda              14.875000  19.262000  13.351000
p_fcf_last_year         0.000038   0.000044  -0.000072
ev_fcf                 35.736380  35.736380  16.213300
ps_ttm                  6.856470   9.980900   8.548620
ev_s                    4.475888   8.324256   7.953868
pb                     32.249540   7.063120  17.510180
profit_margin          21.502190  34.960880   7.880950
revenue_growth          3.270410  36.822640  29.817910
ebitda_growth          -1.097100  37.055540  33.940320
roe_income             23.210420  22.352220   9.767770
roaa_income             0.161000   0.153000   0.061000
roic_income             0.212000   0.301000   0.298000
roe_ebitda              0.762452   0.330007   1.829645
roa_ebitda              0.231256   0.229074   0.353431
roic_ebitda             0.252389   0.370493   1.330320
current_ratio           1.141750   6.080210   1.269510
assets_to_liabilities   1.364830   4.126477   1.287273

In [89]:
mins = df_no_measure_type.min(axis=1)
for measure in mins.index:
    # df.iloc[:,:-1].loc[measure] += abs(mins.loc[measure])
    df_no_measure_type.loc[measure] += abs(mins.loc[measure])
    # df.loc[:,symbols_cols].loc[measure] += abs(mins.loc[measure]) # does not work
df_no_measure_type

                            AAPL         FB       NFLX
pe_ttm                 87.708200  49.766060  87.708200
ev_ebitda              28.226000  32.613000  26.702000
p_fcf_last_year         0.000110   0.000116   0.000000
ev_fcf                 51.949680  51.949680  32.426600
ps_ttm                 13.712940  16.837370  15.405090
ev_s                    8.951775  12.800144  12.429755
pb                     39.312660  14.126240  24.573300
profit_margin          29.383140  42.841830  15.761900
revenue_growth          6.540820  40.093050  33.088320
ebitda_growth           0.000000  38.152640  35.037420
roe_income             32.978190  32.119990  19.535540
roaa_income             0.222000   0.214000   0.122000
roic_income             0.424000   0.513000   0.510000
roe_ebitda              1.092460   0.660015   2.159652
roa_ebitda              0.460331   0.458148   0.582505
roic_ebitda             0.504778   0.622882   1.582710
current_ratio           2.283500   7.221960   2.411260
assets_to_liabilities   2.652103   5.413750   2.574546

In [90]:
df[df_no_measure_type.columns] = df_no_measure_type
df

                            AAPL         FB       NFLX measure_type
pe_ttm                 87.708200  49.766060  87.708200    valuation
ev_ebitda              28.226000  32.613000  26.702000    valuation
p_fcf_last_year         0.000110   0.000116   0.000000    valuation
ev_fcf                 51.949680  51.949680  32.426600    valuation
ps_ttm                 13.712940  16.837370  15.405090    valuation
ev_s                    8.951775  12.800144  12.429755    valuation
pb                     39.312660  14.126240  24.573300    valuation
profit_margin          29.383140  42.841830  15.761900      quality
revenue_growth          6.540820  40.093050  33.088320      quality
ebitda_growth           0.000000  38.152640  35.037420      quality
roe_income             32.978190  32.119990  19.535540      quality
roaa_income             0.222000   0.214000   0.122000      quality
roic_income             0.424000   0.513000   0.510000      quality
roe_ebitda              1.092460   0.660015   2.159652      quality
roa_ebitda              0.460331   0.458148   0.582505      quality
roic_ebitda             0.504778   0.622882   1.582710      quality
current_ratio           2.283500   7.221960   2.411260      quality
assets_to_liabilities   2.652103   5.413750   2.574546      quality

In [94]:
df_no_measure_type.loc['pe_ttm'].sum()

225.18246000000002

In [96]:
df_copy = df_no_measure_type.copy().copy()

In [99]:
df_copy.loc['new_r0w'] = 10 / df_copy.loc['pe_ttm']

In [102]:
df.loc['pe_ttm']['measure_type']

'valuation'

In [103]:
for measure in df_no_measure_type.index:
    measure_sum = df_no_measure_type.loc[measure].sum()
    row_name = measure + '_weight'
    if df.loc[measure]['measure_type'] == 'valuation':
        df_no_measure_type.loc[row_name] = 1 - (df_no_measure_type.loc[measure] / measure_sum)
    elif df.loc[measure]['measure_type'] == 'quality':
        df_no_measure_type.loc[row_name] = df_no_measure_type.loc[measure] / measure_sum

TypeError: unsupported operand type(s) for /: 'str' and 'float'